service: awslambdaexpress

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
